# Generated by Django 3.0.4 on 2020-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, default='dupa', max_length=256, null=True),
        ),
    ]
